# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js base image for building
FROM node:20-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy package.json and pnpm-lock.yaml to the working directory
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the TypeScript code
RUN npm run build

# Use a fresh Node.js image to reduce image size
FROM node:20-alpine

# Set the working directory in the new container
WORKDIR /app

# Copy the build output and node_modules from the builder stage
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# Set environment variables (These will need to be provided at runtime)
ENV POCKET_CONSUMER_KEY=your-pocket-consumer-key
ENV POCKET_ACCESS_TOKEN=your-pocket-access-token

# Command to run the application
CMD ["node", "dist/index.js"]
